# Generated by Django 3.1 on 2020-09-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('serviceID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('serviceName', models.CharField(max_length=128, unique=True)),
                ('serviceType', models.CharField(max_length=128, unique=True)),
                ('serviceMRP', models.FloatField(max_length=10, null=True)),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(null=True)),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
            ],
        ),
    ]
