# Generated by Django 3.1 on 2020-09-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_jobcardservices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobcardServices',
        ),
    ]
