# Generated by Django 3.1 on 2020-09-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_servicedetails_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='serviceType',
            field=models.CharField(max_length=128),
        ),
    ]
