# Generated by Django 3.1 on 2020-09-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_delete_jobcardservices'),
        ('services', '0005_auto_20200908_1206'),
    ]

    operations = [
    ]
