# Generated by Django 3.1 on 2020-09-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_merge_20200909_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='isDeleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
