# Generated by Django 3.1 on 2022-02-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20201221_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='serviceName',
            field=models.CharField(max_length=128),
        ),
    ]
