# Generated by Django 3.1 on 2022-02-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20220202_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
