# Generated by Django 3.1 on 2020-10-12 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0008_auto_20200910_1608'),
        ('customer', '0019_remove_customerdetail_signature'),
        ('workshop', '0010_auto_20201008_1023'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReminder',
            fields=[
                ('sdID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('reminderDate', models.DateTimeField()),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
                ('cusID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerdetail')),
                ('serviceID', models.ManyToManyField(related_name='many_services', to='services.ServiceDetails')),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshopID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.workshopdetail')),
            ],
        ),
    ]
