# Generated by Django 3.1 on 2020-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceReminder', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicereminder',
            index=models.Index(fields=['reminderDate', '-createdAt'], name='serviceRemi_reminde_e37958_idx'),
        ),
    ]
