# Generated by Django 3.1 on 2020-08-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('cusID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cusname', models.CharField(max_length=255)),
                ('cusaddress', models.CharField(max_length=500)),
                ('cusemail', models.EmailField(max_length=254)),
                ('cusphone', models.CharField(max_length=10, unique=True)),
                ('remarks', models.CharField(max_length=255)),
                ('cussignature', models.ImageField(upload_to='')),
            ],
        ),
    ]
