# Generated by Django 3.1 on 2020-08-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200827_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetail',
            old_name='userId',
            new_name='userID',
        ),
    ]
