# Generated by Django 3.1 on 2020-09-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customerdetail_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='cusaddress',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='remarks',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
