# Generated by Django 3.1 on 2020-09-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20200904_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='cusaddress',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
