# Generated by Django 3.1 on 2020-09-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20200908_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='isDeleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
