# Generated by Django 3.1 on 2020-09-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20200910_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='cussignature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
