# Generated by Django 3.1 on 2020-09-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20200921_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetail',
            name='cussignature',
        ),
    ]
