# Generated by Django 3.1 on 2020-09-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_customerdetail_cussignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='cussignature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
