# Generated by Django 3.1 on 2020-10-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20201007_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetail',
            old_name='cussignature',
            new_name='cus_signature',
        ),
    ]
