# Generated by Django 3.1 on 2020-10-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_customerdetail_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetail',
            name='signature',
        ),
    ]
