# Generated by Django 3.1 on 2022-02-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20201221_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
