# Generated by Django 3.1 on 2020-08-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesdetail',
            name='fuelIndicator',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
