# Generated by Django 3.1 on 2020-08-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehiclesdetail_cusid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclesdetail',
            name='cusID',
        ),
    ]
