# Generated by Django 3.1 on 2020-09-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20200904_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesdetail',
            name='kilometer',
            field=models.FloatField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclesdetail',
            name='vehiclenumber',
            field=models.CharField(max_length=18),
        ),
    ]
