# Generated by Django 3.1 on 2020-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_auto_20200914_1707'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehiclesdetail',
            index=models.Index(fields=['vehiclenumber', 'chasisnumber', 'enginenumber', '-createdAt'], name='vehicles_ve_vehicle_257ff1_idx'),
        ),
    ]
