# Generated by Django 3.1 on 2020-09-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartDetails',
            fields=[
                ('partID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('partName', models.CharField(max_length=128, unique=True)),
                ('partType', models.CharField(max_length=128, unique=True)),
                ('partPrice', models.FloatField(max_length=10, null=True)),
                ('partNumber', models.CharField(max_length=128, null=True)),
                ('rackNumber', models.CharField(max_length=128, null=True)),
                ('HSNNumber', models.CharField(max_length=128, null=True)),
                ('companyName', models.CharField(max_length=128, null=True)),
                ('partNote', models.CharField(max_length=128, null=True)),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField()),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
            ],
        ),
    ]
