# Generated by Django 3.1 on 2020-09-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20200910_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partdetails',
            name='HSNNumber',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='partdetails',
            name='companyName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='partdetails',
            name='isDeleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='partdetails',
            name='partNote',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='partdetails',
            name='partNumber',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='partdetails',
            name='partPrice',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='partdetails',
            name='rackNumber',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
