# Generated by Django 3.1 on 2020-10-22 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendormanager'),
        ('parts', '0006_auto_20200923_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedParts',
            fields=[
                ('partID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('partName', models.CharField(max_length=128)),
                ('partType', models.CharField(max_length=128)),
                ('partPrice', models.FloatField(blank=True, max_length=10, null=True)),
                ('partNumber', models.CharField(blank=True, max_length=128, null=True)),
                ('rackNumber', models.CharField(blank=True, max_length=128, null=True)),
                ('HSNNumber', models.CharField(blank=True, max_length=128, null=True)),
                ('companyName', models.CharField(blank=True, max_length=128, null=True)),
                ('partNote', models.CharField(blank=True, max_length=128, null=True)),
                ('vendorPartQty', models.IntegerField(blank=True, null=True)),
                ('vendorPartPrice', models.FloatField(blank=True, max_length=12, null=True)),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
                ('vendorID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendordetail')),
            ],
        ),
    ]
