# Generated by Django 3.1 on 2020-10-22 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_requestedparts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedparts',
            old_name='partID',
            new_name='reqpartID',
        ),
    ]
