# Generated by Django 3.1 on 2020-11-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_auto_20201022_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedparts',
            name='isAdded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
