# Generated by Django 3.1 on 2020-11-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_requestedparts_isadded'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReuestPartPhoneOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('otp_session_id', models.CharField(default='', max_length=120, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='requestedparts',
            name='isAdded',
        ),
    ]
