# Generated by Django 3.1 on 2020-11-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_requestedparts_isadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='partdetails',
            name='partMedia',
            field=models.JSONField(null=True),
        ),
    ]
