# Generated by Django 3.1 on 2020-11-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_partdetails_partmedia'),
        ('parts', '0010_auto_20201111_1023'),
    ]

    operations = [
    ]
