# Generated by Django 3.1 on 2020-11-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0012_requestedparts_partmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='partdetails',
            name='modelNumber',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='partdetails',
            name='varient',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='partdetails',
            name='vehicleModel',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='requestedparts',
            name='modelNumber',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='requestedparts',
            name='varient',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='requestedparts',
            name='vehicleModel',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
