# Generated by Django 3.1 on 2020-11-23 06:46

import VehiclesLabs.aws.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0014_partimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartVideo',
            fields=[
                ('partVidID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('partVidName', models.CharField(blank=True, max_length=256, null=True)),
                ('PartVideo', models.FileField(blank=True, null=True, storage=VehiclesLabs.aws.utils.MediaRootS3BotoStorage(), upload_to='')),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
            ],
        ),
    ]
