# Generated by Django 3.1 on 2020-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0015_partvideo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='partdetails',
            index=models.Index(fields=['partName', 'partType', 'partNumber', 'rackNumber', 'HSNNumber', 'companyName', 'vehicleModel', 'modelNumber', 'varient', '-createdAt'], name='parts_partd_partNam_2cf877_idx'),
        ),
        migrations.AddIndex(
            model_name='partimage',
            index=models.Index(fields=['partImgName', '-createdAt'], name='parts_parti_partImg_984e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='partvideo',
            index=models.Index(fields=['partVidName', '-createdAt'], name='parts_partv_partVid_4fec92_idx'),
        ),
        migrations.AddIndex(
            model_name='requestedparts',
            index=models.Index(fields=['partName', 'partType', 'partNumber', 'rackNumber', 'HSNNumber', 'companyName', 'vehicleModel', 'modelNumber', 'varient', '-createdAt'], name='parts_reque_partNam_6182d2_idx'),
        ),
    ]
