# Generated by Django 3.1 on 2021-01-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0016_auto_20201221_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partdetails',
            name='rackNumber',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
