# Generated by Django 3.1 on 2021-01-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_auto_20210112_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partdetails',
            name='rackNumber',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
