# Generated by Django 3.1 on 2021-01-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0018_auto_20210112_1037'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='partdetails',
            name='parts_partd_partNam_2cf877_idx',
        ),
        migrations.AddIndex(
            model_name='partdetails',
            index=models.Index(fields=['partName', 'partType', 'partNumber', 'HSNNumber', 'companyName', 'vehicleModel', 'modelNumber', 'varient', '-createdAt'], name='parts_partd_partNam_debb8e_idx'),
        ),
    ]
