# Generated by Django 3.1 on 2021-01-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0019_auto_20210112_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partdetails',
            name='rackNumber',
        ),
    ]
