# Generated by Django 3.1 on 2021-01-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0020_remove_partdetails_racknumber'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='partdetails',
            name='parts_partd_partNam_debb8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='requestedparts',
            name='parts_reque_partNam_6182d2_idx',
        ),
        migrations.RemoveField(
            model_name='partdetails',
            name='modelNumber',
        ),
        migrations.RemoveField(
            model_name='requestedparts',
            name='modelNumber',
        ),
        migrations.AddIndex(
            model_name='partdetails',
            index=models.Index(fields=['partName', 'partType', 'partNumber', 'HSNNumber', 'companyName', 'vehicleModel', 'varient', '-createdAt'], name='parts_partd_partNam_2be7c4_idx'),
        ),
        migrations.AddIndex(
            model_name='requestedparts',
            index=models.Index(fields=['partName', 'partType', 'partNumber', 'HSNNumber', 'companyName', 'vehicleModel', 'varient', '-createdAt'], name='parts_reque_partNam_20b76e_idx'),
        ),
    ]
