# Generated by Django 3.1 on 2021-01-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0021_auto_20210112_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='partdetails',
            name='blockIndex',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='partdetails',
            name='localName',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='partdetails',
            name='page',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='partdetails',
            name='refNo',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
