# Generated by Django 3.1 on 2021-01-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0022_auto_20210112_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedparts',
            name='blockIndex',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='requestedparts',
            name='localName',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='requestedparts',
            name='page',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='requestedparts',
            name='refNo',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='partdetails',
            name='partName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='partdetails',
            name='partType',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requestedparts',
            name='partName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requestedparts',
            name='partType',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
