# Generated by Django 3.1 on 2021-01-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0023_auto_20210112_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partdetails',
            name='blockIndex',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='partdetails',
            name='localName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='partdetails',
            name='page',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='partdetails',
            name='refNo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='partdetails',
            name='varient',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='partdetails',
            name='vehicleModel',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requestedparts',
            name='blockIndex',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requestedparts',
            name='localName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requestedparts',
            name='page',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requestedparts',
            name='refNo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requestedparts',
            name='varient',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requestedparts',
            name='vehicleModel',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
