# Generated by Django 3.1 on 2021-01-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0024_auto_20210112_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partdetails',
            name='partMedia',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
