# Generated by Django 3.1 on 2020-12-03 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('creditAmount', models.FloatField(blank=True, null=True)),
                ('debitAmount', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('refType', models.CharField(blank=True, choices=[('Jobcard', 'jobcard'), ('CounterSale', 'countersale'), ('VendorSaleCard', 'vendorsalecard')], max_length=128, null=True)),
                ('refID', models.IntegerField(blank=True, null=True)),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('isActivated', models.BooleanField(default=True, null=True)),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
