# Generated by Django 3.1 on 2020-09-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaDetails',
            fields=[
                ('mediaID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mediaType', models.CharField(choices=[('1', 'Image'), ('2', 'Video')], max_length=15)),
                ('mediaURL', models.CharField(max_length=15, null=True)),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField()),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
            ],
        ),
    ]
