# Generated by Django 3.1 on 2020-09-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20200908_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadetails',
            name='isDeleted',
            field=models.BooleanField(null=True),
        ),
    ]
