# Generated by Django 3.1 on 2020-09-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20200909_1635'),
        ('media', '0003_auto_20200909_1741'),
    ]

    operations = [
    ]
