# Generated by Django 3.1 on 2020-09-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_merge_20200910_1531'),
        ('media', '0005_auto_20200910_1608'),
    ]

    operations = [
    ]
