# Generated by Django 3.1 on 2020-09-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_merge_20200914_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadetails',
            name='mediaURL',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
