# Generated by Django 3.1 on 2020-09-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_auto_20200918_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadetails',
            name='mediaURL',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
