# Generated by Django 3.1 on 2020-09-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20200918_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediadetails',
            name='mediaFor',
        ),
    ]
