# Generated by Django 3.1 on 2020-10-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_remove_mediadetails_mediafor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadetails',
            name='mediaURL',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
