# Generated by Django 3.1 on 2020-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_auto_20201006_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadetails',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediadetails',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
