# Generated by Django 3.1 on 2020-10-09 04:43

import VehiclesLabs.aws.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_auto_20201006_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadetails',
            name='mediaURL',
            field=models.FileField(blank=True, null=True, storage=VehiclesLabs.aws.utils.StaticRootS3BotoStorage(), upload_to=''),
        ),
    ]
