# Generated by Django 3.1 on 2020-10-12 07:31

import VehiclesLabs.aws.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_auto_20201009_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadetails',
            name='mediaURL',
            field=models.FileField(blank=True, null=True, storage=VehiclesLabs.aws.utils.MediaRootS3BotoStorage(), upload_to=''),
        ),
    ]
