# Generated by Django 3.1 on 2020-09-08 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
        ('services', '0004_remove_servicedetails_userid'),
        ('jobcards', '0003_jobcarddetail_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarddetail',
            name='partID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.partdetails'),
        ),
        migrations.AddField(
            model_name='jobcarddetail',
            name='serviceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicedetails'),
        ),
    ]
