# Generated by Django 3.1 on 2020-09-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0004_auto_20200908_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcarddetail',
            name='partID',
        ),
        migrations.RemoveField(
            model_name='jobcarddetail',
            name='serviceID',
        ),
    ]
