# Generated by Django 3.1 on 2020-09-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0004_jobcardservices'),
        ('jobcards', '0005_auto_20200908_1218'),
    ]

    operations = [
    ]
