# Generated by Django 3.1 on 2020-09-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0006_merge_20200908_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardservices',
            name='Services',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
