# Generated by Django 3.1 on 2020-09-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0007_jobcardservices_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcardservices',
            old_name='Services',
            new_name='services',
        ),
    ]
