# Generated by Django 3.1 on 2020-09-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0006_merge_20200908_1515'),
        ('jobcards', '0008_auto_20200908_1739'),
    ]

    operations = [
    ]
