# Generated by Django 3.1 on 2020-09-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0010_remove_jobcardservices_serviceprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardservices',
            name='servicePrice',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='jobcardservices',
            name='servicePrices',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
