# Generated by Django 3.1 on 2020-09-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0011_auto_20200909_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcardservices',
            name='servicePrice',
        ),
        migrations.RemoveField(
            model_name='jobcardservices',
            name='servicePrices',
        ),
    ]
