# Generated by Django 3.1 on 2020-09-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0012_auto_20200909_1820'),
        ('jobcards', '0009_merge_20200909_1626'),
    ]

    operations = [
    ]
