# Generated by Django 3.1 on 2020-09-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0013_merge_20200910_1530'),
        ('jobcards', '0016_auto_20200911_1048'),
    ]

    operations = [
    ]
