# Generated by Django 3.1 on 2020-09-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0017_merge_20200914_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarddetail',
            name='totalServiceAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
