# Generated by Django 3.1 on 2020-09-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0018_jobcarddetail_totalserviceamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcarddetail',
            name='totalServiceAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
    ]
