# Generated by Django 3.1 on 2020-09-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0020_auto_20200915_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcarddetail',
            name='totalPartsAmount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='jobcarddetail',
            name='totalServiceAmount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
