# Generated by Django 3.1 on 2020-09-15 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20200910_1608'),
        ('jobcards', '0021_auto_20200915_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardparts',
            name='partsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.partdetails'),
        ),
    ]
