# Generated by Django 3.1 on 2020-09-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0022_auto_20200915_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcardparts',
            old_name='partsID',
            new_name='partID',
        ),
    ]
