# Generated by Django 3.1 on 2020-09-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorinventory', '__first__'),
        ('jobcards', '0023_auto_20200915_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcardparts',
            old_name='parts',
            new_name='partQtys',
        ),
        migrations.RemoveField(
            model_name='jobcardparts',
            name='partID',
        ),
        migrations.AddField(
            model_name='jobcardparts',
            name='partQty',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='jobcardparts',
            name='vendorInventoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendorinventory.vendorinventory'),
        ),
        migrations.AddField(
            model_name='jobcardparts',
            name='vendorInventoryIDs',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
