# Generated by Django 3.1 on 2020-09-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshopinventory', '__first__'),
        ('jobcards', '0024_auto_20200915_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcardparts',
            old_name='vendorInventoryIDs',
            new_name='workshopInventoryIDs',
        ),
        migrations.RemoveField(
            model_name='jobcardparts',
            name='vendorInventoryID',
        ),
        migrations.AddField(
            model_name='jobcardparts',
            name='workshopInventoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshopinventory.workshopinventory'),
        ),
    ]
