# Generated by Django 3.1 on 2020-09-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0026_auto_20200916_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarddetail',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='jobcardparts',
            name='partQty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
