# Generated by Django 3.1 on 2020-10-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0027_auto_20200917_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarddetail',
            name='due',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='jobcarddetail',
            name='isComepleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='jobcarddetail',
            name='paid',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
