# Generated by Django 3.1 on 2020-10-05 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0028_auto_20201005_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcarddetail',
            old_name='isComepleted',
            new_name='isCompleted',
        ),
    ]
