# Generated by Django 3.1 on 2020-10-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0029_auto_20201005_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarddetail',
            name='deliveredAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcarddetail',
            name='expectedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
