# Generated by Django 3.1 on 2020-10-13 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0019_remove_customerdetail_signature'),
        ('jobcards', '0031_jobcardimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopCustomer',
            fields=[
                ('workshopCustomerID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
                ('cusID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerdetail')),
                ('userID', models.ForeignKey(blank=True, default=150, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
