# Generated by Django 3.1 on 2020-10-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0032_workshopcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarddetail',
            name='discountAmount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='jobcarddetail',
            name='newTotal',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
