# Generated by Django 3.1 on 2020-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0035_auto_20201214_1410'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobcarddetail',
            index=models.Index(fields=['expectedAt', 'deliveredAt', '-createdAt'], name='jobcards_jo_expecte_d09d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcardparts',
            index=models.Index(fields=['-createdAt'], name='jobcards_jo_created_38713b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcardservices',
            index=models.Index(fields=['-createdAt'], name='jobcards_jo_created_251884_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopcustomer',
            index=models.Index(fields=['-createdAt'], name='jobcards_wo_created_674c67_idx'),
        ),
    ]
