# Generated by Django 3.1 on 2020-09-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='status',
            new_name='is_read',
        ),
    ]
