# Generated by Django 3.1 on 2020-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200930_1721'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['-createdAt'], name='notificatio_created_d3b564_idx'),
        ),
    ]
