# Generated by Django 3.1 on 2020-10-26 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0019_remove_customerdetail_signature'),
        ('vendors', '0010_auto_20201022_1454'),
        ('workshop', '0015_auto_20201022_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSaleCard',
            fields=[
                ('vendorsalecardID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('saleType', models.CharField(blank=True, choices=[('Workshop', 'Workshop'), ('Customer', 'Customer')], max_length=128, null=True)),
                ('total', models.FloatField(blank=True, default=0.0, null=True)),
                ('paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('due', models.FloatField(blank=True, default=0.0, null=True)),
                ('discountAmount', models.FloatField(blank=True, default=0.0, null=True)),
                ('newTotal', models.FloatField(blank=True, default=0.0, null=True)),
                ('delivered', models.BooleanField(default=False, null=True)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False, null=True)),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
                ('cusID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerdetail')),
                ('vendorID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendordetail')),
                ('workshopID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.workshopdetail')),
            ],
        ),
    ]
