# Generated by Django 3.1 on 2020-10-26 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_auto_20201022_1127'),
        ('vendorinventory', '0005_vendorinventory_excel_file'),
        ('vendorsalecard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPartSale',
            fields=[
                ('vendorPartSaleID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('partQty', models.IntegerField(blank=True, null=True)),
                ('partPrice', models.FloatField(blank=True, default=0.0, null=True)),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
                ('partID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.partdetails')),
                ('vendorInventoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendorinventory.vendorinventory')),
                ('vendorsalecardID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendorsalecard.vendorsalecard')),
            ],
        ),
    ]
