# Generated by Django 3.1 on 2020-12-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorsalecard', '0003_vendorsalecard_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorsalecard',
            name='delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
