# Generated by Django 3.1 on 2020-12-09 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorsalecard', '0004_auto_20201208_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorpartsale',
            name='vendorsalecardID',
        ),
        migrations.AddField(
            model_name='vendorsalecard',
            name='partSaleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendorsalecard.vendorpartsale'),
        ),
    ]
