# Generated by Django 3.1 on 2020-10-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInquiry',
            fields=[
                ('inquiryID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(blank=True, max_length=450, null=True)),
                ('ownerPhone', models.CharField(blank=True, max_length=10, null=True)),
                ('ownerName', models.CharField(blank=True, max_length=250, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1200, null=True)),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
            ],
        ),
    ]
