# Generated by Django 3.1 on 2020-09-28 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0006_auto_20200923_1213'),
        ('customer', '0012_auto_20200921_2150'),
        ('services', '0008_auto_20200910_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterSale',
            fields=[
                ('countersaleID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
                ('cusID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerdetail')),
                ('partID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.partdetails')),
                ('seviceID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicedetails')),
            ],
        ),
    ]
