# Generated by Django 3.1 on 2020-09-28 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshopinventory', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countersale', '0004_countersaleparts_countersaleservices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countersaleparts',
            old_name='jobID',
            new_name='countersaleID',
        ),
        migrations.RemoveField(
            model_name='countersaleparts',
            name='partQtys',
        ),
        migrations.RemoveField(
            model_name='countersaleparts',
            name='workshopInventoryIDs',
        ),
        migrations.RemoveField(
            model_name='countersaleservices',
            name='servicePrices',
        ),
        migrations.RemoveField(
            model_name='countersaleservices',
            name='services',
        ),
        migrations.AddField(
            model_name='countersale',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countersale',
            name='workshopinventoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshopinventory.workshopinventory'),
        ),
    ]
