# Generated by Django 3.1 on 2020-09-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countersale', '0005_auto_20200928_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countersaleparts',
            name='partsPrices',
        ),
    ]
