# Generated by Django 3.1 on 2020-09-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countersale', '0007_auto_20200928_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countersaleservices',
            name='countersaleID',
        ),
        migrations.RemoveField(
            model_name='countersaleservices',
            name='serviceID',
        ),
        migrations.RemoveField(
            model_name='countersale',
            name='totalPartsAmount',
        ),
        migrations.RemoveField(
            model_name='countersale',
            name='totalServiceAmount',
        ),
        migrations.AddField(
            model_name='countersale',
            name='Serviceprice',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='countersale',
            name='servicename',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='countersale',
            name='vehicleNumber',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='CounterSaleParts',
        ),
        migrations.DeleteModel(
            name='CounterSaleServices',
        ),
    ]
