# Generated by Django 3.1 on 2020-09-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countersale', '0009_minorservices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countersale',
            old_name='Serviceprice',
            new_name='erviceprice',
        ),
        migrations.RenameField(
            model_name='countersale',
            old_name='vehicleNumber',
            new_name='vehiclenumber',
        ),
    ]
