# Generated by Django 3.1 on 2020-09-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countersale', '0010_auto_20200929_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countersale',
            old_name='erviceprice',
            new_name='serviceprice',
        ),
    ]
