# Generated by Django 3.1 on 2020-10-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countersale', '0011_auto_20200929_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='countersale',
            name='due',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='countersale',
            name='isCompleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='countersale',
            name='paid',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
