# Generated by Django 3.1 on 2020-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countersale', '0012_auto_20201005_1116'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='countersale',
            index=models.Index(fields=['vehiclenumber', 'servicename', 'isCompleted', '-createdAt'], name='countersale_vehicle_8662d6_idx'),
        ),
    ]
