# Generated by Django 3.1 on 2020-08-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('FuelID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Fueltype', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
