# Generated by Django 3.1 on 2020-08-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fueltype', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fueltype',
            old_name='FuelID',
            new_name='fuelID',
        ),
        migrations.RenameField(
            model_name='fueltype',
            old_name='Fueltype',
            new_name='fueltype',
        ),
    ]
