# Generated by Django 3.1 on 2020-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fueltype', '0005_auto_20200910_1608'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fueltype',
            index=models.Index(fields=['fueltype', '-createdAt'], name='fueltype_fu_fueltyp_b28bee_idx'),
        ),
    ]
