# Generated by Django 3.1 on 2020-09-28 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiclebrands', '0004_auto_20200910_1608'),
        ('services', '0008_auto_20200910_1608'),
        ('workshop', '0005_auto_20200910_1646'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0012_auto_20200921_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('appointID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vehiclenumber', models.CharField(max_length=18)),
                ('appointDate', models.DateTimeField()),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
                ('brandID', models.ForeignKey(default=150, on_delete=django.db.models.deletion.CASCADE, to='vehiclebrands.vehiclebrand')),
                ('cusID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerdetail')),
                ('serviceID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicedetails')),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshopID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.workshopdetail')),
            ],
        ),
        migrations.CreateModel(
            name='AppointServices',
            fields=[
                ('appointServicesID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
                ('appointID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerBookAppointment.bookappointment')),
                ('serviceID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicedetails')),
            ],
        ),
    ]
