# Generated by Django 3.1 on 2020-09-29 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20200910_1608'),
        ('customerBookAppointment', '0003_bookappointment_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='servicesID',
            field=models.ManyToManyField(related_name='many_service', to='services.ServiceDetails'),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='serviceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_service', to='services.servicedetails'),
        ),
    ]
