# Generated by Django 3.1 on 2020-09-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerBookAppointment', '0004_auto_20200929_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointment',
            name='serviceID',
        ),
        migrations.RemoveField(
            model_name='bookappointment',
            name='services',
        ),
        migrations.DeleteModel(
            name='AppointServices',
        ),
    ]
