# Generated by Django 3.1 on 2020-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerBookAppointment', '0005_auto_20200929_1654'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookappointment',
            index=models.Index(fields=['vehiclenumber', 'appointDate', '-createdAt'], name='customerBoo_vehicle_2b28f1_idx'),
        ),
    ]
