# Generated by Django 3.1 on 2020-10-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopinventory', '0002_auto_20200930_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopinventory',
            name='due',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='workshopinventory',
            name='orderCompleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='workshopinventory',
            name='paid',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
