# Generated by Django 3.1 on 2020-10-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopinventory', '0003_auto_20201007_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopinventory',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
