# Generated by Django 3.1 on 2020-10-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopinventory', '0004_workshopinventory_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopinventory',
            name='delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
