# Generated by Django 3.1 on 2020-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopinventory', '0005_workshopinventory_delivered'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workshopinventory',
            index=models.Index(fields=['-createdAt'], name='workshopinv_created_e2d4c6_idx'),
        ),
    ]
