# Generated by Django 3.1 on 2020-09-18 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetail',
            fields=[
                ('vendorID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vendorname', models.CharField(max_length=20)),
                ('vendoremail', models.EmailField(max_length=254)),
                ('vendorphone', models.CharField(max_length=10)),
                ('vendoraddress', models.CharField(max_length=200)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
