# Generated by Django 3.1 on 2020-10-06 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_auto_20201006_0954'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordetail',
            name='logo',
        ),
        migrations.AddField(
            model_name='vendordetail',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.mediadetails'),
        ),
    ]
