# Generated by Django 3.1 on 2020-10-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20201006_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetail',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
