# Generated by Django 3.1 on 2020-10-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendordetail_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetail',
            name='expected_days',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendordetail',
            name='gst_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vendordetail',
            name='gst_per',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='vendordetail',
            name='invoice_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
