# Generated by Django 3.1 on 2020-10-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_auto_20201007_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetail',
            name='expectedDay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
