# Generated by Django 3.1 on 2020-10-08 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendordetail_expectedday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordetail',
            name='expected_days',
        ),
    ]
