# Generated by Django 3.1 on 2020-10-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendormanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormanager',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendormanager',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
