# Generated by Django 3.1 on 2020-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_auto_20201022_1454'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendordetail',
            index=models.Index(fields=['vendorname', 'vendoremail', 'vendorphone', '-createdAt'], name='vendors_ven_vendorn_f9cbfc_idx'),
        ),
        migrations.AddIndex(
            model_name='vendormanager',
            index=models.Index(fields=['-createdAt'], name='vendors_ven_created_30bd2f_idx'),
        ),
    ]
