# Generated by Django 3.1 on 2020-09-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200921_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='useraddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
