# Generated by Django 3.1 on 2020-09-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200924_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='utype',
            field=models.CharField(blank=True, choices=[('Admin', 'admin'), ('Workshop Owner', 'workshop_owner'), ('Vendor', 'vendor'), ('Customer', 'customer')], max_length=128, null=True),
        ),
    ]
