# Generated by Django 3.1 on 2020-09-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200928_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
