# Generated by Django 3.1 on 2020-09-30 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200928_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='expiredAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 15, 13, 0, 37, 573924)),
        ),
    ]
