# Generated by Django 3.1 on 2020-09-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userdetail_enddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='endDate',
            new_name='trialendAt',
        ),
    ]
