# Generated by Django 3.1 on 2020-09-30 10:30

from django.db import migrations, models
import src.apis.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userdetail_expiredat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='expiredAt',
            field=models.DateTimeField(default=src.apis.accounts.models.get_expiredAt),
        ),
    ]
