# Generated by Django 3.1 on 2020-10-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200930_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='utype',
            field=models.CharField(blank=True, choices=[('Admin', 'admin'), ('Workshop Owner', 'workshop_owner'), ('Workshop User', 'workshop_user'), ('Vendor', 'vendor'), ('Customer', 'customer')], max_length=128, null=True),
        ),
    ]
