# Generated by Django 3.1 on 2020-10-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201003_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='isActivated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
