# Generated by Django 3.1 on 2020-10-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userdetail_isactivated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='isActivated',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
