# Generated by Django 3.1 on 2020-10-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201005_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='profileimage',
        ),
    ]
