# Generated by Django 3.1 on 2020-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userdetail_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
