# Generated by Django 3.1 on 2020-10-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200929_1748'),
        ('accounts', '0011_userdetail_profileimage'),
    ]

    operations = [
    ]
