# Generated by Django 3.1 on 2020-10-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_subscriptionrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionrecord',
            name='expiredAt',
        ),
    ]
