# Generated by Django 3.1 on 2020-10-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_subscriptionrecord_expiredat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('subTypeID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.IntegerField()),
                ('timePeriod', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('subType', models.CharField(blank=True, choices=[('Premium', 'premium'), ('Normal', 'normal')], max_length=128, null=True)),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriptionrecord',
            name='isActivated',
        ),
    ]
