# Generated by Django 3.1 on 2020-10-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201014_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrecord',
            name='paymentID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionrecord',
            name='paymentStatus',
            field=models.BooleanField(default=False),
        ),
    ]
