# Generated by Django 3.1 on 2020-10-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20201014_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionrecord',
            name='paymentStatus',
        ),
    ]
