# Generated by Django 3.1 on 2020-10-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_subscriptionrecord_paymentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='subType',
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='subName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
