# Generated by Django 3.1 on 2020-10-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201015_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrecord',
            name='razor_res',
            field=models.JSONField(null=True),
        ),
    ]
