# Generated by Django 3.1 on 2020-11-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20201021_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='utype',
            field=models.CharField(blank=True, choices=[('Admin', 'admin'), ('Workshop Owner', 'workshop_owner'), ('Workshop User', 'workshop_user'), ('Vendor', 'vendor'), ('Customer', 'customer'), ('Workshop Manager', 'workshop_manager'), ('Vendor Manager', 'vendor_manager'), ('Marketeer', 'marketeer')], max_length=128, null=True),
        ),
    ]
