# Generated by Django 3.1 on 2020-09-01 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardPermission',
            fields=[
                ('permID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('create_jobcard', models.BooleanField(blank=True, null=True)),
                ('edit_jobcard', models.BooleanField(blank=True, null=True)),
                ('view_jobcard', models.BooleanField(blank=True, null=True)),
                ('delete_jobcard', models.BooleanField(blank=True, null=True)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
