# Generated by Django 3.1 on 2020-09-01 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rolepermission', '0002_auto_20200901_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('permID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('create_jobcard', models.BooleanField(blank=True, null=True)),
                ('edit_jobcard', models.BooleanField(blank=True, null=True)),
                ('view_jobcard', models.BooleanField(blank=True, null=True)),
                ('delete_jobcard', models.BooleanField(blank=True, null=True)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
