# Generated by Django 3.1 on 2020-09-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0003_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
