# Generated by Django 3.1 on 2020-09-23 12:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0004_delete_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='jobcard',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Create'), ('2', 'Update'), ('3', 'Delete'), ('4', 'View')], max_length=4, null=True),
        ),
    ]
