# Generated by Django 3.1 on 2020-09-23 13:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0005_permissions_jobcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='create_jobcard',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='delete_jobcard',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='edit_jobcard',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='view_jobcard',
        ),
        migrations.AddField(
            model_name='permissions',
            name='inventory',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('View', 'View')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='jobcard',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('View', 'View')], max_length=25, null=True),
        ),
    ]
