# Generated by Django 3.1 on 2020-09-24 04:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0006_auto_20200923_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='counterSale',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('View', 'View')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='permissions',
            name='workshop',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('View', 'View')], max_length=25, null=True),
        ),
    ]
