# Generated by Django 3.1 on 2020-09-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0007_auto_20200924_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='permissions',
            name='createdBy',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='permissions',
            name='isDeleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='permissions',
            name='meta',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='permissions',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='permissions',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
