# Generated by Django 3.1 on 2020-09-24 11:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0008_auto_20200924_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='counterSale',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Update', 'Update'), ('View', 'View')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='inventory',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Update', 'Update'), ('View', 'View')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='jobcard',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Update', 'Update'), ('View', 'View')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='workshop',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Update', 'Update'), ('View', 'View')], max_length=25, null=True),
        ),
    ]
