# Generated by Django 3.1 on 2020-09-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0009_auto_20200924_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='counterSale',
        ),
    ]
