# Generated by Django 3.1 on 2020-09-25 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rolepermission', '0011_permissions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='user_workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wokrshop_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wokrshop_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
