# Generated by Django 3.1 on 2020-09-28 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_auto_20200910_1646'),
        ('rolepermission', '0012_auto_20200925_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='workshopID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.workshopdetail'),
        ),
    ]
