# Generated by Django 3.1 on 2020-09-30 03:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0013_permissions_workshopid'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='counter_sale',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Update', 'Update'), ('View', 'View')], max_length=25, null=True),
        ),
    ]
