# Generated by Django 3.1 on 2020-11-10 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rolepermission', '0014_permissions_counter_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketeer',
            fields=[
                ('mID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('admin_report', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Update', 'Update'), ('View', 'View')], max_length=25, null=True)),
                ('subscription_plan', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Update', 'Update'), ('View', 'View')], max_length=25, null=True)),
                ('user', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Update', 'Update'), ('View', 'View')], max_length=25, null=True)),
                ('capture_payment', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Update', 'Update'), ('View', 'View')], max_length=25, null=True)),
                ('requested_parts', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Update', 'Update'), ('View', 'View')], max_length=25, null=True)),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=120, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=120, null=True)),
                ('marketerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketeer', to=settings.AUTH_USER_MODEL)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
