# Generated by Django 3.1 on 2020-11-19 06:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0015_marketeer'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketeer',
            name='part',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Update', 'Update'), ('View', 'View')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='marketeer',
            name='service',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Update', 'Update'), ('View', 'View')], max_length=25, null=True),
        ),
    ]
