# Generated by Django 3.1 on 2020-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0016_auto_20201119_1153'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marketeer',
            index=models.Index(fields=['-createdAt'], name='rolepermiss_created_38d00e_idx'),
        ),
        migrations.AddIndex(
            model_name='permissions',
            index=models.Index(fields=['-createdAt'], name='rolepermiss_created_15ab42_idx'),
        ),
    ]
