# Generated by Django 3.1 on 2020-09-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorinventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorCustomer',
        ),
    ]
