# Generated by Django 3.1 on 2020-09-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorinventory', '0002_delete_vendorcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinventory',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
