# Generated by Django 3.1 on 2020-09-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorinventory', '0003_vendorinventory_excel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorinventory',
            name='excel_file',
        ),
    ]
