# Generated by Django 3.1 on 2020-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorinventory', '0005_vendorinventory_excel_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendorinventory',
            index=models.Index(fields=['-createdAt'], name='vendorinven_created_cef94d_idx'),
        ),
    ]
