# Generated by Django 3.1 on 2020-08-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('brandID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('brandname', models.CharField(max_length=50, null=True)),
                ('brandmodel', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
