# Generated by Django 3.1 on 2020-09-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclebrands', '0003_vehiclebrand_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclebrand',
            name='isDeleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
