# Generated by Django 3.1 on 2022-02-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclebrands', '0005_auto_20201221_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebrand',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
