# Generated by Django 3.1 on 2020-09-21 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0011_auto_20200915_0943'),
        ('vendorinventory', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCustomer',
            fields=[
                ('vendorCustomerID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cusPartQty', models.IntegerField(blank=True, null=True)),
                ('cusPartPrice', models.FloatField(blank=True, max_length=15, null=True)),
                ('meta', models.JSONField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('createdBy', models.CharField(max_length=120)),
                ('updatedBy', models.CharField(max_length=120)),
                ('cusID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerdetail')),
                ('vendorInventoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendorinventory.vendorinventory')),
            ],
        ),
    ]
