# Generated by Django 3.1 on 2020-09-22 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('vendorcustomer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcustomer',
            name='vendorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendordetail'),
        ),
    ]
