# Generated by Django 3.1 on 2020-09-23 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20200910_1608'),
        ('vendorcustomer', '0002_vendorcustomer_vendorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcustomer',
            name='partsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.partdetails'),
        ),
    ]
