# Generated by Django 3.1 on 2020-09-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorcustomer', '0003_vendorcustomer_partsid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorcustomer',
            old_name='partsID',
            new_name='partID',
        ),
    ]
