# Generated by Django 3.1 on 2020-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorcustomer', '0005_vendorcustomer_delivered'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendorcustomer',
            index=models.Index(fields=['-createdAt'], name='vendorcusto_created_d86fcb_idx'),
        ),
    ]
