# Generated by Django 3.1 on 2020-10-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_workshopdetail_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopdetail',
            name='expected_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopdetail',
            name='gst_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='workshopdetail',
            name='gst_per',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='workshopdetail',
            name='invoice_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
