# Generated by Django 3.1 on 2020-10-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_auto_20201007_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopdetail',
            name='expected_day',
        ),
        migrations.AddField(
            model_name='workshopdetail',
            name='expected_days',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
