# Generated by Django 3.1 on 2020-10-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_auto_20201021_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopmanager',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopmanager',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
