# Generated by Django 3.1 on 2020-10-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0014_auto_20201022_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopmanager',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='workshopmanager',
            name='longitude',
        ),
    ]
