# Generated by Django 3.1 on 2020-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0015_auto_20201022_1454'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workshopdetail',
            index=models.Index(fields=['workshopname', 'workshopemail', 'workshopphone', '-createdAt'], name='workshop_wo_worksho_6ac378_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopmanager',
            index=models.Index(fields=['-createdAt'], name='workshop_wo_created_40c38b_idx'),
        ),
    ]
